config/routes.rb
Rails.application.routes.draw do
  root "appointments#index"

  resources :doctors do
    resources :appointments, only: [:index, :new, :create, :destroy]
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_doctor
  def index
    @gp = @doctor.appointments.where(specialty: 'general practitioner')
    @opto = @doctor.appointments.where(specialty: 'optometry')
    @dent = @doctor.appointments.where(specialty: 'dentistry')
  end
# In the interest of keeping my project similar to the lesson and not falling back to previous project frameworks,
# I decided to give the doctors specialties that essentially work like roles do in the lesson.
# I also decided to make everyone's appointments visible to all, even though that would violate HIPAA guidelines.
  def show
  end

  def new
    @appointment = @doctor.appointments.new
  end

  def create
    @appointment = @doctor.appointments.new(appointment_params)
    if @appointment.save
      redirect_to @appointment
    else
      render :new
    end
  end
  # I considered giving the option to edit appointments, but the information used for appointments is being pulled from the faker gem, 
  # and I would rather not take the time to make a schedule template for fake doctors 

  def destroy
    @appointment = @doctor.appointments.find(params[:id])
    @appointment.destroy
    redirect_to doctor_appointments_path(@doctor)
  end

  private
  def set_doctor
    @doctor = Doctor.find(params[:doctor_id])
# This is the 2nd time that I haven't been able to find a model id while in a nested model's controller. I would legit like some help understanding what I'm doing wrong
# I've checked the routes in the localhost routes page, and the doctor id is in the show url, but it's still not showing up
# I've also checked all instances of the nested model in the rails console and they do have a doctor's id, so I'm not sure why I can't pull up doctor info
  end

  def appointment_params
    params.require(:appointment).permit(:time, :user_id)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :destroy]
  def index
    @doctors = Doctors.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to @doctor 
    else
      render :new
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_page
  end

  private
  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:name, :specialty)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy]
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end


  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/edit.html.erb
<h1>Appointments#edit</h1>
<p>Find me in app/views/appointments/edit.html.erb</p>

app/views/appointments/index.html.erb
<h1>Appointments#index</h1>
<p>Find me in app/views/appointments/index.html.erb</p>

app/views/appointments/new.html.erb
<h1>Appointments#new</h1>
<p>Find me in app/views/appointments/new.html.erb</p>

app/views/appointments/show.html.erb
<h1>Appointments#show</h1>
<p>Find me in app/views/appointments/show.html.erb</p>

app/views/doctors/edit.html.erb
<h1>Doctors#edit</h1>
<p>Find me in app/views/doctors/edit.html.erb</p>

app/views/doctors/index.html.erb
<h1>Doctors#index</h1>
<p>Find me in app/views/doctors/index.html.erb</p>

app/views/doctors/new.html.erb
<h1>Doctors#new</h1>
<p>Find me in app/views/doctors/new.html.erb</p>

app/views/doctors/show.html.erb
<h1>Doctors#show</h1>
<p>Find me in app/views/doctors/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <ul>
    <li>
      <%= link_to 'Doctors', doctors_path %>
    </li>
    <li>
      <%= link_to 'New Doctor', new_doctor_path %>
    </li>
    <li>
      <%= link_to 'Users', users_path %>
    </li>
    <li>
      <%= link_to 'Add User', new_user_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocOffice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>